### ISSUE TITLE
gschema is only read from the extension directory

### ISSUE THREAD

**Issue by terencode** [Selenium-H/Notification-Center#12]
```
Settings schema 'org.gnome.shell.extensions.notification-center' does not contain a key named 'max-height'
== Stack trace for context 0x557337b82270 ==
#0   5573390b3680 i   /usr/share/gnome-shell/extensions/notification-center@Selenium-H/extension.js:111 (7fccb556dca0 @ 222)
#1   7fffe5042f60 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fcce5fb98b0 @ 71)
#2   5573390b35c8 i   /usr/share/gnome-shell/extensions/notification-center@Selenium-H/extension.js:47 (7fccb556d820 @ 300)
#3   7fffe5043ed0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fcce5fb98b0 @ 71)
#4   5573390b3540 i   /usr/share/gnome-shell/extensions/notification-center@Selenium-H/extension.js:22 (7fccb556d700 @ 15)
#5   7fffe5045300 b   resource:///org/gnome/shell/ui/extensionSystem.js:131 (7fcce5c47f70 @ 504)
#6   7fffe50453a0 b   resource:///org/gnome/shell/ui/extensionSystem.js:285 (7fcce5c4c4c0 @ 13)
#7   7fffe5045490 b   self-hosted:261 (7fcce5fc05e0 @ 223)
#8   5573390b33f0 i   resource:///org/gnome/shell/ui/extensionSystem.js:282 (7fcce5c4c3a0 @ 75)
```

ArchLinux
Gnome 3.32.1

**Comment by goodwillcoding** [comment]
@terencode that looks like you do not have compiles schemas for the installed extension. How did you install it?
For references ... this is the line that compiles the schemas: https://github.com/Selenium-H/Notification-Center/blob/master/INSTALL.sh#L35

**Comment by terencode** [comment]
@goodwillcoding yes you are right I made an AUR package for it : https://aur.archlinux.org/packages/gnome-shell-extension-notification-center-git/ and this time I added the org.gnome.shell.extensions.notification-center.gschema.xml to /usr/share/glib-2.0/schemas  which gets recompiled automatically when the package is installed but although I can see in dconf-editor the entries are being created, but gnome-shell complains it can't find the  gschemas.compiled inside the extension folder.

**Comment by Selenium-H** [comment]
@terencode  In PKGBUILD file replace Line 25
install  -Dm644 notification-center@Selenium-H/schemas/*.xml -t "$pkgdir/usr/share/glib-2.0/schemas/"
with
glib-compile-schemas "$pkgdir/usr/share/gnome-shell/extensions/notification-center@Selenium-H/schemas".

This will compile schemas in schemas folder inside the extension folder which is read by extension.

**Comment by terencode** [comment]
@Selenium-H I think for PKBUILDs it's better to include those small scripts in them and customize them for archLinux packaging guidelines.

I checked some other extensions PKBUILD but I don't understand why it isn't reading the global gschemas.compiled in /usr/share/glib-2/ but instead the one in the extension folder.

**Comment by Selenium-H** [comment]
@terencode Thanks for maintaining the extension in AUR. Sorry I forgot in previous comment.
Currently since a schemas folder is present inside extension folder, It is coded only to read the compiled schemas from that folder inside the extension folder. 
https://github.com/Selenium-H/Notification-Center/blob/eb12dca3d078b9bea78b1cf3c377bbe78cbda109/notification-center%40Selenium-H/extension.js#L41

**Comment by terencode** [comment]
@Selenium-H No problem, Thanks for explaining I understand better now. I'll make some temporary changes to account for that.

Maybe you could try to get inspiration from dash-to-dock which seems to be able to use either a compiled schema in its extension folder or the all in one in /usr/share/glib-2/ .

**Comment by Selenium-H** [comment]
Version 16 can read global schemas and translations.

**Comment by terencode** [comment]
Thanks!
