### ISSUE TITLE
Close the notification panel after click to open a notification

### ISSUE THREAD

**Issue by srgcdev** [Selenium-H/Notification-Center#14]
When I click to open a notification in the notification panel, the notification panel keeps open.
It would be nice that the notification panel it closes when I click to open a notification.

I have the extension Noannoyance installed too but I think the behaviour is the same if this extension is not installed.

Thanks in advance.

**Comment by Selenium-H** [comment]
Last commit added and option to close notification panel when clicked on notification and focus to any window.
