### ISSUE TITLE
Could not delete runtime/persistent state file

### ISSUE THREAD

**Issue by terencode** [Selenium-H/Notification-Center#16]
I regularly see the the following in the log: 
`Could not delete runtime/persistent state file: Error removing file /home/terence/.local/share/gnome-shell/notifications`

**Comment by Selenium-H** [comment]
Is the error showing up with this extension disabled ?

**Comment by terencode** [comment]
I don't think so but I'll test.
Although, since my last reboot after updating the extension to your last commit, I didn't encounter it.

**Comment by terencode** [comment]
Can't see it anymore.
