### ISSUE TITLE
[meta] Git Workflow

### ISSUE THREAD

**Issue by terencode** [Selenium-H/Notification-Center#17]
First, thank you for creating this extension and keeping it updated.

What I think would greatly help you and people looking at the repo is to properly leverage what git allows you to do.

Right now, all your commits message are not useful because they just describe how you are using git right now: as a way to upload files. 
However, if one wants to get a changelog, or understand what a recent commit did, it's harder.
It's also not just for others to look at what you did, but for you: it makes you track what you did, and you don't have to open the files again just to see what you worked on recently.

Another problem is that those commits seem to be atomic sometimes: multiple unrelated changes merged into one single commit. The problem with this approach is that you can't properly isolate what code comes from a single change. If for example a change you made wasn't right or you changed your mind, with one change per commit, you can just use `git revert [commit hash]` that will just undo what the corresponding commit contained. You can't do that if one commit contains multiple separate changes.

There are numerous websites like https://githowto.com that provides a tutorial to better grasp the different concepts if you need.

**Comment by Selenium-H** [comment]
Thanks for letting me know and the link. I will make sure that commit messages are related to the changes done.
