### ISSUE TITLE
Do not disturb: no indicator when auto-hide is enabled

### ISSUE THREAD

**Issue by terencode** [Selenium-H/Notification-Center#19]
Right now, when you enable the "do not disturb" mode the bell icon goes grey. 
However, if you enabled the auto hide option, you will not have any feedback that this mode is active.
I suggest disabling auto-hide when "do not disturb" is active and replacing the bell icon with a circle backslash.

**Comment by Selenium-H** [comment]
Last commit in [Version-17-not-final](https://github.com/Selenium-H/Notification-Center/tree/Version-17-not-final) branch added an option to disable autohide if do not disturb mode is enabled.

**Comment by terencode** [comment]
Thanks, I tested it and it's nicely done :).
A suggestion: hide "Detected missing messages. Rebuilding" into a debug options with other stuffs you could put in there for later debugging.
