### ISSUE TITLE
Notification Center Icon - Flash

### ISSUE THREAD

**Issue by sirkuttin** [Selenium-H/Notification-Center#2]
I'd love if the icon could flash for unread notifications. Setting up a blacklist of applications to ignore would be great.

**Comment by sirkuttin** [comment]
here is an example of flashing notifications. https://extensions.gnome.org/extension/258/notifications-alert-on-user-menu/

**Comment by Selenium-H** [comment]
blink Icon added in last commit

**Comment by Selenium-H** [comment]
Application blacklist added.
