### ISSUE TITLE
Remove vertical separator

### ISSUE THREAD

**Issue by amivaleo** [Selenium-H/Notification-Center#28]
Hi!

Look at the picture:

![Schermata da 2020-04-05 14-29-10](https://user-images.githubusercontent.com/24316547/78495905-20cfdc80-774a-11ea-84d4-16bf66763c25.png)

Is it possible to remove that vertical separator?

**Comment by Selenium-H** [comment]
With last commit vertical separator is now removed when all three sections are removed from datetime menu.
