### ISSUE TITLE
Error loading on Gnome 3.30

### ISSUE THREAD

**Issue by fawtytoo** [Selenium-H/Notification-Center#29]
TypeError: this.dndItem is undefined
Error: Extension point conflict: there is already a status indicator for role NotificationCenter

**Comment by Selenium-H** [comment]
Can you please state the preferences options that are changed ?

Also try removing the extension followed by GNOME Shell restart and then reinstalling the extension from GitHub as explained [here](https://github.com/Selenium-H/Notification-Center#manualgnome-shell-extension-website) in `Manual` column of `Installation` section.

**Comment by fawtytoo** [comment]
I installed from Git and that appears to have fixed the issue. Thanks.
