### ISSUE TITLE
Not working on GNOME 3.38

### ISSUE THREAD

**Issue by giovannicaligaris** [Selenium-H/Notification-Center#36]
I can't enable the extension

**Comment by evfool** [comment]
Error message is `No property x_fill on StScrollView`

**Comment by evfool** [comment]
After resolving the x_fill, the next error is a `setDate` function missing, after commenting out all the `setDate` calls the next thing is `Expected and object of type ClutterActor as argument 'actor' but got undefined`, and this is where I gave up, as the fix would need more investigation than I can invest at this moment (after investigating and fixing 3 broken extensions - with merge requests filed for all fixes- on GNOME-Shell 3.38.0 update, I can understand the frustrations of GNOME Shell extension developers).

If any help is needed by the developers of this extension for testing, I am happy to help.

**Comment by Selenium-H** [comment]
Last commit in [experimental](https://github.com/Selenium-H/Notification-Center/tree/experimental) branch added GNOME Shell 3.38 support.

**Comment by giovannicaligaris** [comment]
Is working now, but the notifications area still shows under calendar.

![Screenshot from 2020-10-09 17-52-08](https://user-images.githubusercontent.com/26255347/95610470-4b338700-0a58-11eb-824b-ba604be364c4.png)

**Comment by Selenium-H** [comment]
@giovannicaligaris, Please, set `Space Beside Calendar Menu` option to  `Hide if Empty` in the extension preferences. If it's still there then disable and enable the extension or restart GNOME Shell.

**Comment by giovannicaligaris** [comment]
It works, thanks!
