### ISSUE TITLE
The clear all button not working on Fedora 33

### ISSUE THREAD

**Issue by JerryPenguin** [Selenium-H/Notification-Center#39]
Since I switched to Fedora 33, the Clear Button no longer works.
It was not an update but a fresh installation on a new SSD.
I have already removed and reinstalled the extension several times, both from the GNONE Extionsionsion Sites and the GIT repository.
The button clear has no function anymore.

**Comment by Selenium-H** [comment]
Last commit in `master` branch fixed this issue.

**Comment by JerryPenguin** [comment]
Thanks a lot, it works :-)
