### ISSUE TITLE
Keyboard shortcut to open notification pannel

### ISSUE THREAD

**Issue by mwensveen-ebpi** [Selenium-H/Notification-Center#42]
It would be very nice if the notification panel can be opened with a keyboard shortcut.
Like SUPER+M does for the standard notification tray

**Comment by Selenium-H** [comment]
Implemented with last commit in [experimental](https://github.com/Selenium-H/Notification-Center/tree/experimental) `branch`

**Comment by mwensveen-ebpi** [comment]
I tried to install the extentions from  expirimental branch. Unfortunately I see an error in Tweak tools. 
Running Ubuntu 18.04.5 LTS, gnome 3.28.2

```
TypeError: ExtensionUtils.initTranslations is not a function

Stack trace:
  init@/home/user/.local/share/gnome-shell/extensions/notification-center@Selenium-H/prefs.js:25:3
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:76:9
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
  @<main>:1:43
 
```

**Comment by Selenium-H** [comment]
Please try installing it from [Version-18.01](https://github.com/Selenium-H/Notification-Center/tree/Version-18.01) `branch`. It's now added there.

**Comment by mwensveen-ebpi** [comment]
I can install version 18.01 and it  works. Thanks.

**Comment by grational** [comment]
How to actually open the notification panel? Inside the notification center preferences, I spotted `Super + C` but, using it, I toggle between the notification icon being shown or not. The notification panel is not opened in any case (Ubuntu 20.04.02 Gnome 3.36.5).
