### ISSUE TITLE
[Request] Additional options when notification received from specific applications

### ISSUE THREAD

**Issue by MostHated** [Selenium-H/Notification-Center#44]
Hey there,
    This seems like a great addon. Just started using it a few minutes ago and saw there was a list you could specify options for individual applications. It would be awesome if you could do additional actions per application when a notification is received. I know it's a bit of a stretch, but an example of something that would be great to be able to do is, if I have my volume down then if I get a notification from Telegram from a specific person, be able to have that notification make a noise, but then the volume is back down otherwise. 

    I realize that is way more difficult, so to be able to perhaps simply specify a script to run if a notification comes from an application, then I could try to handle the action on my own. That way I could have a script that runs on a Discord notification, one for Slack, etc, etc. 

Either way, I appreciate the time you have put into this addon, 
Thanks,
-MH

**Comment by Selenium-H** [comment]
Sorry for the delay. This is now implemented in [ongoing](https://github.com/Selenium-H/Notification-Center/tree/ongoing) `branch`. 
If you are updating from a previous version please reset the extension from `Preferences Top Right Menu` -> `Preferences` ->  `Reset notification Center Extension` after updating.
Please enable `Run scripts on new notification` in `Preferences` -> `Profiles`. After selecting the application from the list, the location of the script is to be manually added (for the time being) in `Preferences` -> `Profiles` -> `Custom script location`. Click on `set`. 
For removing the script select the application and delete the entry in  `Custom script location` and click on `set`.
