### ISSUE TITLE
Change the notification banner  location from  top to bottom  

### ISSUE THREAD

**Issue by KonstantMan** [Selenium-H/Notification-Center#45]
I found about this amazing extension searching for a way to  change my discord notification location so it would be nice to have the option to change the notification banner  location from  top to bottom

**Comment by Selenium-H** [comment]
Sorry for the delay. This is now implemented in [ongoing](https://github.com/Selenium-H/Notification-Center/tree/ongoing) `branch`. 
If you are updating from previous version please reset the extension from `Preferences Top Right Menu` -> `Preferences` ->  `Reset notification Center Extension` after updating.
