### ISSUE TITLE
Resize the date-time panel according to the daily events

### ISSUE THREAD

**Issue by amivaleo** [Selenium-H/Notification-Center#46]
Hi!

My apologies for the bad title. Well, it is a bad title to me at least, but I can't find a better one.

Look at this picture:

![a](https://user-images.githubusercontent.com/24316547/111472701-84b89e80-872a-11eb-941e-4e8ecb6773c9.png)

On the left, today, it shows I have three reminders. If I click on another day, like yesterday, in which I had no events in agenda, the panel height remains the same and its content shift downward so to align vertically.

Is it possible to avoid this behaviour by resizing the popover accordingly?

**Comment by Selenium-H** [comment]
Sorry for the delay. This is fixed with last commit in [ongoing](https://github.com/Selenium-H/Notification-Center/tree/ongoing) `branch`. 
Please reset the extension from `Preferences Top Right Menu` -> `Preferences` ->  `Reset notification Center Extension` after updating.

**Comment by amivaleo** [comment]
Thank you! :)

I'm going to wait for these updates to land in gnome extension website. :+1:
