### ISSUE TITLE
Leave calendar notification in the calendar, only "move" regular notification

### ISSUE THREAD

**Issue by goodwillcoding** [Selenium-H/Notification-Center#5]
Hi, currently when notifications are "moved" to the Notification Center the calendar ones come along with it, which disables the functionality of to navigating the calendar (when one clicks different dates the calendar notifications for that date show)

Is it possible to only move the regular notification (or clone the calendar ones) to the Notification center and have the calendar ones remain next to the clock.

![noyification-center](https://user-images.githubusercontent.com/582074/54496575-09f3e900-48ae-11e9-82ab-7e6f645f8019.png)

**Comment by Selenium-H** [comment]
Yes, it can be done. I will update it shortly.

**Comment by Selenium-H** [comment]
Added settings to keep events list besides calendar or not to move them at all.

**Comment by goodwillcoding** [comment]
@Selenium-H ... thank you ... top notch extension
