### ISSUE TITLE
Gnome 41 Support?

### ISSUE THREAD

**Issue by Scotty-Trees** [Selenium-H/Notification-Center#52]
Greetings,

Gnome 41 was released this month and I was wondering if/when the extension will be updated? Thank you for your time and thank you for making an amazing extension I couldn't live without! Cheers

**Comment by Selenium-H** [comment]
The extension will be updated for `GNOME 41` after its final release.

**Comment by kyteinsky** [comment]
Hey @Selenium-H,
I am using GNOME 41 and this extension does not do anything as the prefs say. It does not even throw any error. I would love if you ported it to 41.

Thanks.
